### ISSUE TITLE
Need some help converting from jsfive to h5wasm

### ISSUE THREAD

**Issue by aLemonFox** [usnistgov/h5wasm#15] opened 2022-04-11 10:13 UTC
Hi, first of all, thanks a lot for your work. Your libs are exactly what I need but I'm having some trouble building to javascript. Since jsfive doesnt have any TypeScript support I am planning on re-writing everything in this library, however when I run my postinstall script `tsc`, I get the following errors: 
```
node_modules/h5wasm/src/emscripten.d.ts:52:33 - error TS2304: Cannot find name 'WebGLRenderingContext'.

52     preinitializedWebGLContext: WebGLRenderingContext;
                                   ~~~~~~~~~~~~~~~~~~~~~

node_modules/h5wasm/src/emscripten.d.ts:66:28 - error TS2304: Cannot find name 'MessageEvent'.

66     onCustomMessage(event: MessageEvent): void;

... 9 more similar errors
```

Do I need to configure something in order for it to work? I am using Node v16.5.0

**Comment by bmaranville** [comment] 2022-04-11 14:08
Both these issues seem to be related to not having the TypeScript ```dom``` definitions.  Are you compiling a nodejs application?

The emscripten types in h5wasm are a modified version of the DefinitelyTyped ones at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/emscripten and the part that seems to be giving difficulty is not a part that I modified.

Neither of these types is used in h5wasm (MessageEvent or WebGLRenderingContext).  Someone in [this thread](https://github.com/ReactiveX/rxjs/issues/1986) suggested you can set ```--skipLibCheck```, and others at the end of the thread suggested that the problem is not seen in later versions of tsc.

**Comment by aLemonFox** [comment] 2022-04-11 14:31
Yeah it's just a nodejs application. Setting `"skipLibCheck": true` fixes the issue so seems to have something to do with TypeScript. However this library is the only one generating an error message.

**Comment by bmaranville** [comment] 2022-04-11 14:35
Since at the moment I am already committed to a custom types file for emscripten, I might as well remove those entries as they are not used.  Then in the next release of h5wasm the issue would go away.

If you feel like testing this hypothesis for me - you could go into your node_modules/h5wasm folder and edit emscripten.d.ts and comment out lines 52 and 66 and see if it fixes the problem!

**Comment by aLemonFox** [comment] 2022-04-11 14:36
Sure, will try right now :)

**Comment by aLemonFox** [comment] 2022-04-11 14:42
I no longer get the error when commenting out those lines, so that seems to work. I however do still get some other errors which were also included in the original error message:
```
node_modules/h5wasm/src/hdf5_util_helpers.d.ts:39:5 - error TS7010: 'create_dataset', which lacks return-type annotation, implicitly has an 'any' return type.

39     create_dataset(file_id: bigint, arg1: string, arg2: bigint, arg3: bigint[], type: number, size: number, signed: boolean, vlen: boolean);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

But that's just because I have set `"strict": true` in `tsconfig`.

**Comment by bmaranville** [comment] 2022-04-11 14:46
Ah - I see.  I turned on ```--strict``` and I see them as well.  I will try to fix them all before the next release.

**Comment by aLemonFox** [comment] 2022-04-11 14:47
Awesome! Really appreciate the quick help :)
Cheers man

**Closed** 2022-04-11 14:47 UTC
